name: ASP.NET 😎
on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./net.sln

      - name: Build
        run: dotnet build ./net.sln -- configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./net.sln --configuration Release --no-build
